#! /bin/sh

### Autostart
pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-fill Pictures/wallpaper.jpg

~/.local/bin/polybar.sh

setxkbmap -layout br

### WM config
bspc monitor Virtual1 -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off



